/**
 * FTC kaynak haritası — bütün içerik burada.
 *
 * Sezon değişince yalnızca `kind: 'sezonluk'` işaretli kayıtlara dokunulur.
 * `url` alanı boş bırakılan kayıtlar sayfada "adres bekliyor" rozetiyle
 * görünür; adresi yazdığın anda kart tıklanabilir hâle gelir.
 */

export const LAYERS = {
  resmi: {
    no: '01',
    name: 'Resmî FIRST',
    short: 'Resmî',
    line: 'Kural gücü olan tek katman.',
    body: 'Manual, FTC Docs, Q&A, ödül tanımları. Bir tartışmayı bitiren yer burasıdır.',
    color: '#e0952f',
  },
  dokuman: {
    no: '02',
    name: 'Topluluk dokümanı',
    short: 'Doküman',
    line: "FTC'nin gerçek ders kitabı.",
    body: 'gm0, CTRL ALT FTC, kütüphane dokümanları. Sezon boyunca en çok zaman geçireceğiniz yer.',
    color: '#7fb093',
  },
  canli: {
    no: '03',
    name: 'Canlı topluluk',
    short: 'Topluluk',
    line: 'Yazılı olmayanın sorulduğu yer.',
    body: 'Discord, Chief Delphi, takım kanalları, portfolyo arşivleri. Cevabı yazılmamış sorular buraya gider.',
    color: '#8ab4d8',
  },
};

export const ROLES = {
  kural: 'Kural',
  yazilim: 'Yazılım',
  mekanik: 'Mekanik',
  elektronik: 'Elektronik',
  cad: 'CAD',
  tedarik: 'Tedarik',
  odul: 'Ödül & portfolyo',
  video: 'Video',
};

/** name, layer, roles, kind, desc, url, owner */
export const RESOURCES = [
  // --- katman 1: resmî -----------------------------------------------------
  {
    name: 'Competition Manual',
    layer: 'resmi',
    roles: ['kural'],
    kind: 'sezonluk',
    star: true,
    desc: 'Oyun kuralları, puanlama, robot kısıtları. Sezonun anayasası; tartışma burada başlar ve burada biter.',
    url: 'https://ftc-resources.firstinspires.org/ftc/game',
  },
  {
    name: 'FTC Q&A',
    layer: 'resmi',
    roles: ['kural'],
    kind: 'sezonluk',
    star: true,
    desc: "Kural yorumunun sorulduğu resmî sistem. Cevapları Manual kadar bağlayıcı, çoğu takım varlığını bilmiyor.",
    url: 'https://ftc-qa.firstinspires.org',
  },
  {
    name: 'FTC Events',
    layer: 'resmi',
    roles: ['kural', 'odul'],
    kind: 'sezonluk',
    desc: 'Turnuva sonuçları, skorlar, sıralamalar. Rakip analizinin başlangıç noktası.',
    url: 'https://ftc-events.firstinspires.org',
  },
  {
    name: 'FTC Docs',
    layer: 'resmi',
    roles: ['yazilim', 'elektronik', 'cad'],
    kind: 'kalici',
    star: true,
    desc: 'Teknik tarafın resmî evi: başlangıç rehberleri, kontrol sistemi, SDK, vision, kablolama, ESD, CAD. Çoğu yeni takımın hiç açmadan sezona girdiği kaynak.',
    url: 'https://ftc-docs.firstinspires.org',
  },
  {
    name: 'FTC Docs · Control System',
    layer: 'resmi',
    roles: ['elektronik'],
    kind: 'kalici',
    desc: 'Control Hub ve Expansion Hub konfigürasyonu, bağlantı şeması, self-inspection adımları. Sezon başında bir kez okunması sorulacak sorunun yarısını siliyor.',
    url: 'https://ftc-docs.firstinspires.org',
  },
  {
    name: 'FTC Docs · SDK',
    layer: 'resmi',
    roles: ['yazilim'],
    kind: 'sezonluk',
    desc: 'Robot Controller yazılımı, sürüm güncellemeleri, bilgisayar gereksinimleri. Sezon başında bir kez bakılır, sürüm uyuşmazlığı derdi biter.',
    url: 'https://ftc-docs.firstinspires.org',
  },
  {
    name: 'FTC Docs · CAD ve üretim',
    layer: 'resmi',
    roles: ['cad', 'mekanik'],
    kind: 'kalici',
    desc: 'Resmî tasarım kaynakları ve parça imalat teknikleri.',
    url: 'https://ftc-docs.firstinspires.org',
  },
  {
    name: 'FTC Docs · Vision',
    layer: 'resmi',
    roles: ['yazilim'],
    kind: 'kalici',
    desc: 'VisionPortal, AprilTag, kamera kalibrasyonu, renk işleme. Otonom performansının belirleyicisi artık burada.',
    url: 'https://ftc-docs.firstinspires.org',
  },
  {
    name: 'Robot Wiring Guide',
    layer: 'resmi',
    roles: ['elektronik'],
    kind: 'kalici',
    desc: 'Kablo kesiti, konnektör seçimi, batarya ve güç dağıtımı. Resmî doküman; inceleme de buna göre yapılıyor.',
    url: '',
  },
  {
    name: 'ESD Mitigation analizi',
    layer: 'resmi',
    roles: ['elektronik'],
    kind: 'kalici',
    desc: 'Elektrostatik boşalmaya karşı koruma. Kuru kış aylarında saha kenarında kendiliğinden resetlenen robotların sebebi çoğu zaman bu.',
    url: '',
  },
  {
    name: 'FTC Türkiye',
    layer: 'resmi',
    roles: ['kural', 'tedarik', 'odul'],
    kind: 'kalici',
    star: true,
    desc: "Türkçe giriş katmanı: FTC'ye İlk Adım, takım kayıt kılavuzu, sezon kütüphanesi, Türkçe ödül tanımları, tedarikçi listesi, turnuva takvimi.",
    url: 'https://ftcturkiye.org',
  },

  // --- katman 2: topluluk dokümanı ----------------------------------------
  {
    name: 'Game Manual 0',
    layer: 'dokuman',
    roles: ['yazilim', 'mekanik', 'elektronik', 'tedarik'],
    kind: 'kalici',
    star: true,
    desc: "Tek bir link alacaksanız bu olsun. Açık kaynak, sürekli güncellenen, FTC'nin fiilî ders kitabı: takım kurma, kit rehberi, mekanik tasarım, yazılım kavramları.",
    url: 'https://gm0.org',
  },
  {
    name: 'gm0 · Useful Resources',
    layer: 'dokuman',
    roles: ['kural', 'yazilim', 'mekanik'],
    kind: 'kalici',
    desc: 'Tüm ekosistemin küratörlü link listesi. Bu sayfanın uzun hâli diyebilirsiniz.',
    url: 'https://gm0.org/en/latest/docs/useful-links.html',
  },
  {
    name: 'gm0 · Getting Started in FTC',
    layer: 'dokuman',
    roles: ['kural', 'odul'],
    kind: 'kalici',
    desc: 'Takım kurma, sezon akışı, roller. Bu haftanın ikinci ödevi tam olarak bu bölüm.',
    url: 'https://gm0.org/en/latest/docs/getting-started-in-ftc.html',
  },
  {
    name: 'gm0 · Mechanical Design',
    layer: 'dokuman',
    roles: ['mekanik'],
    kind: 'kalici',
    desc: 'Şasi tipleri, güç aktarımı, mekanizmalar. Mekanik ekibin ana okuma listesi.',
    url: 'https://gm0.org',
  },
  {
    name: 'gm0 · Software Concepts',
    layer: 'dokuman',
    roles: ['yazilim'],
    kind: 'kalici',
    desc: 'Programlama kavramları ve yapılar; kütüphaneye geçmeden önce okunacak bölüm.',
    url: 'https://gm0.org',
  },
  {
    name: 'gm0 · Kit and Hardware Guide',
    layer: 'dokuman',
    roles: ['mekanik', 'tedarik'],
    kind: 'kalici',
    desc: 'Yapı sistemlerini ve motorları tarafsız karşılaştıran bölüm. Marka seçmeden önce okunacak yer.',
    url: 'https://gm0.org',
  },
  {
    name: 'CTRL ALT FTC',
    layer: 'dokuman',
    roles: ['yazilim'],
    kind: 'kalici',
    desc: 'Kontrol teorisini FTC diline çeviren topluluk dokümanı. PID, feedforward, state-space.',
    url: 'https://www.ctrlaltftc.com',
  },
  {
    name: 'Learn Java for FTC',
    layer: 'dokuman',
    roles: ['yazilim'],
    kind: 'kalici',
    desc: "Java'yı sıfırdan öğreten ücretsiz PDF kitap. Programlamaya yeni başlayan için ilk durak.",
    url: '',
  },
  {
    name: 'REV · Introduction to Programming',
    layer: 'dokuman',
    roles: ['yazilim'],
    kind: 'kalici',
    desc: 'Üreticinin kendi programlamaya giriş serisi. Control Hub ile birlikte ilerliyor.',
    url: '',
  },
  {
    name: 'FtcRobotController',
    layer: 'dokuman',
    roles: ['yazilim'],
    kind: 'sezonluk',
    desc: 'Resmî SDK deposu. Her sezon güncellenir; örnek OpMode\'lar burada.',
    url: 'https://github.com/FIRST-Tech-Challenge/FtcRobotController',
  },
  {
    name: 'FTCLib / SolversLib',
    layer: 'dokuman',
    roles: ['yazilim'],
    kind: 'kalici',
    desc: "Komut tabanlı yapı ve donanım soyutlamaları. SolversLib, FTCLib'in aktif bakılan devamı: kütüphaneler yaşar ve ölür, seçmeden önce bakımına bakın.",
    url: '',
  },
  {
    name: 'Road Runner',
    layer: 'dokuman',
    roles: ['yazilim'],
    kind: 'kalici',
    desc: 'Otonom yol takibi. Matematiksel olarak sağlam, kurulumu emek ister.',
    url: '',
  },
  {
    name: 'Pedro Pathing',
    layer: 'dokuman',
    roles: ['yazilim'],
    kind: 'kalici',
    desc: 'Yol takibinde daha kolay ayarlanan, hızla yaygınlaşan alternatif.',
    url: '',
  },
  {
    name: 'NextFTC',
    layer: 'dokuman',
    roles: ['yazilim'],
    kind: 'kalici',
    desc: 'Modern komut/OpMode çatısı. Pedro Pathing eklentisiyle geliyor.',
    url: '',
  },
  {
    name: 'VisionPortal · EasyOpenCV',
    layer: 'dokuman',
    roles: ['yazilim'],
    kind: 'kalici',
    desc: 'Görüntü işleme: AprilTag okuma, renk tespiti, nesne takibi.',
    url: '',
  },
  {
    name: 'FTC Dashboard · Panels',
    layer: 'dokuman',
    roles: ['yazilim'],
    kind: 'kalici',
    desc: 'Canlı telemetri ve ayar arayüzü. Hata ayıklamanın bel kemiği.',
    url: '',
  },
  {
    name: 'ReCalc · EveryCalc',
    layer: 'dokuman',
    roles: ['mekanik'],
    kind: 'kalici',
    star: true,
    desc: "Şasi hızı, motor akımı, mekanizma yükü hesaplayıcıları. Mekanik ekibin ilk refleksi 'deneyip görelim' değil 'önce hesaplayalım' olmalı.",
    url: '',
  },
  {
    name: 'How Gears Work',
    layer: 'dokuman',
    roles: ['mekanik'],
    kind: 'kalici',
    desc: "Bartosz Ciechanowski'nin interaktif yazısı. Dişliyi anlatan muhtemelen en iyi tek sayfa.",
    url: 'https://ciechanow.ski/gears/',
  },
  {
    name: 'SDP-SI · KHK rehberleri',
    layer: 'dokuman',
    roles: ['mekanik'],
    kind: 'kalici',
    desc: 'Kayış-kasnak ve dişli tasarımının endüstriyel referans dokümanları.',
    url: '',
  },
  {
    name: 'FRC Mechanism Encyclopedia',
    layer: 'dokuman',
    roles: ['mekanik'],
    kind: 'kalici',
    desc: 'Mekanizma fikri ararken açılacak katalog. NASA RAP tasarım rehberi de aynı yerde.',
    url: '',
  },
  {
    name: '2901 Purple Gears · Onshape kütüphanesi',
    layer: 'dokuman',
    roles: ['cad'],
    kind: 'kalici',
    desc: 'Hazır FTC parça kütüphanesi. Vidayı sıfırdan çizmek yerine sürükleyip montaja geçiyorsunuz.',
    url: '',
  },
  {
    name: '10650 Hazmat · GrabCAD arşivi',
    layer: 'dokuman',
    roles: ['cad'],
    kind: 'kalici',
    desc: 'Takım tarafından paylaşılan geniş parça arşivi.',
    url: 'https://grabcad.com',
  },
  {
    name: 'ServoCity CAD dosyaları',
    layer: 'dokuman',
    roles: ['cad', 'tedarik'],
    kind: 'kalici',
    desc: 'Üreticinin resmî CAD dosyaları. Montajda ölçü tartışmasını bitiriyor.',
    url: 'https://www.servocity.com',
  },
  {
    name: 'Blender4FTC · Fusion render rehberleri',
    layer: 'dokuman',
    roles: ['cad', 'odul'],
    kind: 'kalici',
    desc: 'Robot görselini portfolyo kalitesinde üretmeyi öğreten rehberler. CAD ile ödül tarafını birleştiren köprü.',
    url: '',
  },

  // --- katman 3: canlı topluluk -------------------------------------------
  {
    name: 'FTC Discord',
    layer: 'canli',
    roles: ['yazilim', 'mekanik', 'kural'],
    kind: 'kalici',
    star: true,
    desc: 'Kod hatası, mekanizma fikri, kural yorumu için gerçek zamanlı yardım. En canlı kanal.',
    url: '',
  },
  {
    name: 'Chief Delphi',
    layer: 'canli',
    roles: ['yazilim', 'mekanik'],
    kind: 'kalici',
    desc: "FRC ve FTC'nin derin teknik tartışma arşivi. Aradığınız sorunun cevabı çoğu zaman zaten yazılmış.",
    url: 'https://www.chiefdelphi.com',
  },
  {
    name: 'Hivemind portfolyo arşivi',
    layer: 'canli',
    roles: ['odul'],
    kind: 'kalici',
    star: true,
    desc: "Yüzlerce takımın gerçek Engineering Portfolio'su açık. Portfolyoda iyi örnek görmek her anlatımdan etkili.",
    url: 'https://portfolios.hivemindrobotics.net',
  },
  {
    name: 'FTC Scout',
    layer: 'canli',
    roles: ['odul', 'kural'],
    kind: 'sezonluk',
    desc: 'Takım ve maç istatistikleri. Turnuva öncesi ittifak stratejisi burada kurulur.',
    url: '',
  },
  {
    name: 'FIRST Tech Challenge · YouTube',
    layer: 'canli',
    roles: ['video', 'kural'],
    kind: 'sezonluk',
    desc: 'Resmî kanal: sezon tanıtımı, oyun animasyonu, kural açıklama videoları, şampiyona yayınları.',
    url: '',
  },
  {
    name: 'REV Robotics · YouTube',
    layer: 'canli',
    roles: ['video', 'elektronik', 'yazilim'],
    kind: 'kalici',
    desc: 'Starter Bot yapım turu, Control Hub kurulumu, programlamaya giriş serisi.',
    url: '',
  },
  {
    name: 'goBILDA · YouTube',
    layer: 'canli',
    roles: ['video', 'mekanik'],
    kind: 'kalici',
    desc: 'Yapı sistemi anlatımları ve Robot-in-3-Days serisi. Sezon başında hızlı prototip için.',
    url: '',
  },
  {
    name: '8644 Brainstormers · Tips & Tricks',
    layer: 'canli',
    roles: ['video', 'mekanik'],
    kind: 'kalici',
    desc: 'FTC mekaniğini en derli toplu anlatan takım serisi.',
    url: '',
  },
  {
    name: '9794 Wizards.exe',
    layer: 'canli',
    roles: ['video', 'mekanik'],
    kind: 'kalici',
    desc: 'Mekanizma tasarımı ve robot tanıtımları; ileri seviye yapım detayları.',
    url: '',
  },
  {
    name: 'Robot reveal videoları',
    layer: 'canli',
    roles: ['video', 'mekanik'],
    kind: 'sezonluk',
    desc: 'Rakip ve örnek tasarımları görmenin en hızlı yolu. Sezon ortasında düzenli tarayın.',
    url: '',
  },

  // --- CAD programları -----------------------------------------------------
  {
    name: 'Onshape',
    layer: 'dokuman',
    roles: ['cad'],
    kind: 'kalici',
    star: true,
    desc: "Tarayıcı tabanlı, kurulum yok, öğrenciye ücretsiz. FTC'de en yaygın tercih.",
    url: 'https://www.onshape.com',
  },
  {
    name: 'Autodesk Fusion · Inventor',
    layer: 'dokuman',
    roles: ['cad'],
    kind: 'kalici',
    desc: 'Eğitim hesabıyla ücretsiz tam sürüm.',
    url: 'https://www.autodesk.com/education',
  },
  {
    name: 'PTC Creo',
    layer: 'dokuman',
    roles: ['cad'],
    kind: 'kalici',
    desc: 'Eğitim lisansı ile tam sürüm erişimi.',
    url: '',
  },
  {
    name: 'SolidWorks',
    layer: 'dokuman',
    roles: ['cad'],
    kind: 'kalici',
    desc: 'Takım sponsorluk programı üzerinden başvuru.',
    url: '',
  },

  // --- yapı sistemleri -----------------------------------------------------
  {
    name: 'goBILDA',
    layer: 'dokuman',
    roles: ['tedarik', 'mekanik'],
    kind: 'kalici',
    desc: 'Kanal ve göbek sistemi, Yellow Jacket motorlar. Takımlara indirim programı var.',
    url: 'https://www.gobilda.com',
  },
  {
    name: 'REV Robotics',
    layer: 'dokuman',
    roles: ['tedarik', 'mekanik', 'elektronik'],
    kind: 'kalici',
    desc: "Ekstrüzyon tabanlı sistem. Control Hub'ın üreticisi olduğu için elektronikle bütünleşik.",
    url: 'https://www.revrobotics.com',
  },
  {
    name: 'TETRIX (Pitsco)',
    layer: 'dokuman',
    roles: ['tedarik', 'mekanik'],
    kind: 'kalici',
    desc: "Pitsco'nun kiti, TorqueNADO motorlar. Okul laboratuvarlarında yaygın.",
    url: 'https://www.pitsco.com',
  },
  {
    name: 'AndyMark',
    layer: 'dokuman',
    roles: ['tedarik', 'mekanik'],
    kind: 'kalici',
    desc: 'Robits yapı sistemi, NeveRest motorlar, mecanum ve compliant tekerlekler.',
    url: 'https://www.andymark.com',
  },
  {
    name: 'Studica',
    layer: 'dokuman',
    roles: ['tedarik', 'mekanik'],
    kind: 'kalici',
    desc: 'Kendi yapı sistemi ve navX IMU sensörü.',
    url: 'https://www.studica.com',
  },

  // --- Türkiye tedarik -----------------------------------------------------
  {
    name: 'NFR Products',
    layer: 'resmi',
    roles: ['tedarik'],
    kind: 'kalici',
    star: true,
    desc: "FRC ve FTC'ye özel üretim: swerve modül, lineer sürüş, mecanum, dişli, gövde elemanı, elektronik ve kit.",
    url: '',
    local: true,
  },
  {
    name: 'Robopiece',
    layer: 'resmi',
    roles: ['tedarik'],
    kind: 'kalici',
    desc: "FTC Türkiye'nin listelediği tedarikçilerden; yarışma parçaları üzerine.",
    url: '',
    local: true,
  },
  {
    name: 'Wattos Otomasyon',
    layer: 'resmi',
    roles: ['tedarik'],
    kind: 'kalici',
    desc: 'Motor, batarya, tekerlek, şasi ve hareket bileşenleri; sezona özel ürün grubu.',
    url: '',
    local: true,
  },
  {
    name: 'ServoCity · Actuonix · Axon',
    layer: 'dokuman',
    roles: ['tedarik', 'elektronik'],
    kind: 'kalici',
    desc: 'Servo ve hareket bileşenleri için yurt dışı adresleri.',
    url: 'https://www.servocity.com',
  },
  {
    name: 'McMaster-Carr · OnlineMetals · MiSUMi · Fastenal',
    layer: 'dokuman',
    roles: ['tedarik', 'mekanik'],
    kind: 'kalici',
    desc: 'Ham malzeme ve hırdavat. Ölçü ve teknik çizim kalitesiyle ayrı bir referans.',
    url: 'https://www.mcmaster.com',
  },
];

/** Sezonun açıldığı gün — slayt 2. */
export const KICKOFF = [
  { big: '12 Eyl', label: 'Oyun tanıtımı ve Competition Manual yayını' },
  { big: '19.00', label: 'Türkiye saatiyle kickoff yayın saati' },
  { big: '~6 ay', label: 'Turnuvalara kadar elimizdeki süre' },
];

/** Yazılımın üç yolu — slayt 9. */
export const PATHS = [
  { no: '1', name: 'Blocks', line: 'Görsel bloklar, tarayıcıdan, sıfır kurulum.', when: 'İlk hafta · ortaokul' },
  { no: '2', name: 'OnBot Java', line: 'Tarayıcıdan gerçek Java. Kurulum yok, kod var.', when: "Blocks'tan Java'ya köprü" },
  { no: '3', name: 'Android Studio', line: 'Tam IDE: sürüm kontrolü, harici kütüphaneler.', when: 'Ciddi sezon yazılımı' },
];

/** Ödüller ve karşılık geldikleri roller — slayt 16-17. */
export const AWARDS = [
  { name: 'Inspire', role: 'Hepsi birden', desc: 'Programın bütününü en iyi yansıtan takım. Bir üst seviyeye ilerlemenin ana yolu.', big: true, roleKey: 'odul' },
  { name: 'Think', role: 'Portfolyo & defter', desc: 'Mühendislik süreci ve mühendislik defteri.', roleKey: 'odul' },
  { name: 'Connect', role: 'Dış ilişkiler', desc: 'STEM topluluğu ve mentör ağı.', roleKey: 'odul' },
  { name: 'Innovate', role: 'Tasarım / CAD', desc: 'Özgün tasarım çözümü.', roleKey: 'cad' },
  { name: 'Control', role: 'Yazılım', desc: 'Sensör, yazılım, otonom.', roleKey: 'yazilim' },
  { name: 'Motivate', role: 'Medya / tanıtım', desc: 'Takım kültürü ve coşku.', roleKey: 'odul' },
  { name: 'Design', role: 'Tasarım / CAD', desc: 'Endüstriyel tasarım dili.', roleKey: 'cad' },
];

/** Bu haftanın görevleri — slayt 20. */
export const TASKS = [
  { id: 't1', text: "Competition Manual'ın ilk bölümünü okuyun. Kuralları değil, yapıyı anlamak için.", hint: 'Competition Manual' },
  { id: 't2', text: 'gm0.org → Getting Started in FTC bölümünü baştan sona okuyun.', hint: 'Game Manual 0' },
  { id: 't3', text: "FTC Discord'a katılın ve takım kanalımızı takibe alın.", hint: 'FTC Discord' },
  { id: 't4', text: 'Onshape eğitim hesabı açın ve ilk parçanızı çizin.', hint: 'Onshape' },
  { id: 't5', text: 'Bir Engineering Portfolio örneği açıp inceleyin ve hangi bölümde çalışmak istediğinize karar verin.', hint: 'Hivemind portfolyo arşivi' },
];

/** Sipariş penceresi — slayt 12'deki uyarının sayısal hâli. */
export const SUPPLY = [
  { max: 2, verdict: 'Sadece elimizdeki parça', tone: 'bad', line: 'İki hafta kala yeni parça beklemek plan değil, umut. Elinizdeki stokla ve yerel hırdavatla çözün.' },
  { max: 4, verdict: 'Türkiye tedarikçisi', tone: 'warn', line: 'Yurt içi sipariş bu pencereye sığar. Yurt dışı sipariş gümrükte kalırsa turnuvaya yetişmez.' },
  { max: 8, verdict: 'Türkiye rahat, yurt dışı riskli', tone: 'ok', line: 'Kritik parçayı yurt içinden alın. Yurt dışı siparişi ancak alternatifi varsa verin.' },
  { max: 99, verdict: 'Her ikisi de açık', tone: 'ok', line: 'Yurt dışı sipariş için doğru zaman burası. Gümrük ve kargo süresini şimdiden takvime yazın.' },
];
