/**
 * Sunum modunun slayt listesi.
 *
 * İçerik data.js'ten gelir; burada yalnızca hangi slaytta ne gösterileceği
 * ve konuşmacı notu durur. Notlar sunumun kendi konuşmacı notlarından.
 */

export const SLIDES = [
  {
    kind: 'cover',
    art: 'robot',
    photo: { file: 'kapak', alt: 'Takım ve robot' },
    eyebrow: 'AG Robotik · Sezon açılışı · 12 Eylül 2026',
    title: ['FTC Kaynakları ve', 'Eğitim Materyalleri'],
    lede: 'Yeni sezona başlarken neyi, nereden öğreneceğiz?',
    foot: 'BIOBUZZ · 2026–2027 FIRST® CANOPY sezonu · Hakan Ataş · Lal Su Narinç · ALKEV Okulları',
    note: 'Açılış. Bugün sezonun açıldığı gün. Sunumun amacı oyunu anlatmak değil, bu sezon boyunca hangi kaynaklara nasıl ulaşacağımızı öğretmek.',
  },
  {
    kind: 'facts',
    art: 'timeline',
    kicker: 'Bugün neredeyiz',
    title: 'Sezon bugün açıldı',
    lede: 'Yani bu sunum bir kütüphane turu değil, bu haftanın yol haritası.',
    callout: "Oyun her yıl değişir, kaynaklar değişmez. BIOBUZZ'ın kuralları bu sezona özel; bugün öğreneceğiniz kaynak haritası mezun olana kadar aynı kalacak.",
    note: 'Öğrencilerin ilk hafta hatası: oyunu ezberlemeye çalışmak. Asıl kazanç kaynak refleksini kurmak.',
  },
  {
    kind: 'dates',
    kicker: 'Kickoff haftası',
    title: 'Takvim bugünden sayıyor',
    lede: 'Manual ön sürümü temmuzda çıktı; tam manual bu akşam. Sonraki iki hafta yazılım ve kural takvimi.',
    foot: 'Team Q&A 28 Eylül\'de açılıyor: o güne kadar kural sorularını biriktirin, açılınca ilk gün yazın.',
    note: 'Tarihler resmî sezon takviminden; slayt bugüne göre kendini hesaplıyor. SDK sürümünü vurgulayın: geçen sezonun SDK\'sıyla kod yazmak inspection\'da geri döndürür.',
  },
  {
    kind: 'two',
    kicker: 'Zihin haritası',
    title: 'İki tür kaynak vardır',
    lede: 'Hangisine ne kadar zaman ayıracağınızı bu ayrım belirler.',
    note: 'Sağ sütun bu sunumun asıl konusu. Sol sütun zaten mecburen okunacak.',
  },
  {
    kind: 'layers',
    kicker: 'Kaynak ekosistemi',
    title: 'Her kaynağın bir sahibi var',
    lede: '{{n}} link ezberlemeyin, üç katmanı öğrenin.',
    note: 'Bu slayt sunumun omurgası. Sonraki her slaydı bir katmana yerleştireceğiz.',
  },
  {
    kind: 'cards',
    names: ['Competition Manual', 'FTC Q&A', 'FTC Events'],
    photo: { file: 'saha', alt: 'Turnuva sahası' },
    kicker: 'Katman 1 — resmî FIRST',
    title: 'Kuralın tek kaynağı',
    lede: 'Buradan gelen bilgi bağlayıcıdır; gerisi yorumdur.',
    foot: 'Bu üç adres sezon boyunca açık sekmede durmalı.',
    note: "Q&A vurgulanmalı: yeni takımların en çok kaçırdığı resmî kaynak. Cevapları Manual kadar bağlayıcı.",
  },
  {
    kind: 'changes',
    items: ['ruh', 'evergreen', 'robot', 'inspection'],
    kicker: 'Bu sezon ne değişti · 1',
    title: 'Manual yeniden yazıldı',
    lede: 'Aynı 18 inç küp, aynı saha mantığı; ama kuralın anlatılma biçimi değişti.',
    foot: 'Kaynak: BIOBUZZ Competition Manual ön sürüm duyurusu. Ayrıntıyı kickoff sonrası tam manual ile doğrulayın.',
    note: 'Satıra tıklayınca büyük puntoyla açılır; tekrar tıklayınca kapanır. "Kuralın ruhu" en önemlisi: hakemle konuşurken madde numarası yerine niyet konuşulacak.',
  },
  {
    kind: 'cards',
    names: ['FTC Docs', 'FTC Docs · Control System', 'FTC Docs · SDK', 'FTC Docs · Vision'],
    photo: { file: 'yazilim', alt: 'Yazılım ekibi masada robotla çalışıyor', short: true },
    kicker: 'Katman 1 — resmî FIRST',
    title: 'FTC Docs: teknik tarafın resmî evi',
    lede: 'Çoğu yeni takımın hiç açmadan sezona girdiği kaynak.',
    foot: 'Vision bölümü ayrı bir parantez hak ediyor: AprilTag ve VisionPortal artık otonom performansının belirleyicisi.',
    note: 'Bu sayfa yazılım ekibinin ilk hafta okuma listesi.',
  },
  {
    kind: 'cards',
    names: ['FTC Türkiye'],
    photo: { file: 'yerel', alt: 'Türkiye turnuvasında hakemler skor masasında', pos: 'center 40%' },
    side: true,
    kicker: 'Katman 1 — yerel',
    title: 'Türkçe giriş katmanı',
    lede: 'İngilizce kaynak yığınına dalmadan önce buradan başlamak işi kolaylaştırır.',
    bullets: [
      "FTC'ye İlk Adım — programa sıfırdan giriş",
      'Takım Kayıt Kılavuzu — kayıt sürecinin adımları',
      'BIOBUZZ Kickoff sayfası ve sezon kütüphanesi',
      'Türkçe ödül tanımları — jürinin neye baktığı',
      'Parça tedarikçileri listesi ve Off-Season rehberi',
    ],
    foot: "Yine de nihai kural kaynağı İngilizce Competition Manual'dır. Türkçe kaynaklar giriş kapısıdır, son söz değil.",
    note: 'Yeni öğrenci için psikolojik olarak önemli: her şey İngilizce değil. Ama son sözü Manual söyler.',
  },
  {
    kind: 'cards',
    names: ['Game Manual 0', 'gm0 · Getting Started in FTC', 'gm0 · Kit and Hardware Guide', 'gm0 · Mechanical Design', 'gm0 · Software Concepts', 'gm0 · Useful Resources'],
    kicker: 'Katman 2 — topluluk dokümanı',
    title: 'Tek bir link alacaksanız, bu olsun',
    lede: "Game Manual 0: açık kaynak, topluluk tarafından sürekli güncellenen, FTC'nin fiilî ders kitabı.",
    note: 'Bu slaytta gerçekten siteyi açıp Useful Resources sayfasını gösterin.',
  },
  {
    kind: 'paths',
    photo: { file: 'kod', alt: 'Android Studio açık bir laptop ve Driver Station telefonu', pos: 'center 35%', short: true },
    kicker: 'Yazılım',
    title: 'Üç programlama yolu, tek yolculuk',
    lede: 'Hepsi aynı robotu sürer. Fark, ne kadar kontrol istediğinizde.',
    foot: "Java'yı sıfırdan öğrenmek için: Learn Java for FTC · REV Introduction to Programming · FtcRobotController deposu. Robot elinizde yokken: FTCSim, tarayıcıda simülatör.",
    note: "Kimse Android Studio'dan başlamak zorunda değil, ama sezon ortasında oraya geçeceğiz.",
  },
  {
    kind: 'cards',
    names: ['FTCSim', 'FTCLib / SolversLib', 'Road Runner', 'Pedro Pathing', 'NextFTC', 'FTC Dashboard · Panels'],
    kicker: 'Yazılım',
    title: 'Araç ve kütüphane haritası',
    lede: 'İlki bugün kullanılır: FTCSim. Gerisini bugün kullanmayacaksınız, ama adını duyduğunuzda ne olduğunu bilin.',
    foot: "Ders: FTCLib'den SolversLib'e geçiş gösteriyor ki kütüphaneler yaşar ve ölür. Seçmeden önce bakımının sürdüğünü kontrol edin.",
    note: "Yeni öğrenciye kaygı vermeden 'var olduğunu bilin' tonuyla geçin.",
  },
  {
    kind: 'cards',
    names: ['goBILDA', 'REV Robotics', 'TETRIX (Pitsco)', 'AndyMark', 'Studica'],
    photo: { file: 'robot', alt: 'Takımın robotu', pos: 'center 72%' },
    kicker: 'Mekanik — tedarik',
    title: 'Beş yapı sistemi, tek saha',
    lede: 'Starter kit sadece giriş kapısı. Beşi de legal ve sahada yan yana yarışıyor.',
    foot: "Sistemler karışabilir. Seçimi marka sadakati değil; elinizdeki parça, bütçe ve teslim süresi belirler. gm0'ın Kit and Hardware Guide bölümü karşılaştırmayı tarafsız yapıyor.",
    note: 'Önemli düzeltme: FTC iki markadan ibaret değil. Takımımızın elindeki mevcut parçalar seçimi büyük ölçüde belirliyor.',
  },
  {
    kind: 'supply',
    kicker: 'Mekanik — tedarik',
    title: 'Önce Türkiye, sonra yurt dışı',
    lede: "FTC Türkiye'nin kendi tedarikçi listesi var: NFR Products, Robopiece, Wattos Otomasyon. Sipariş yolculuğu oradan başlar.",
    foot: 'Yurt dışı: yapı sistemi için goBILDA, REV, Pitsco, AndyMark, Studica · servo ve hareket için ServoCity, Actuonix, Axon · ham malzeme için McMaster-Carr, OnlineMetals, MiSUMi, Fastenal.',
    note: 'Türkiye tedarikçileri kargo ve gümrük derdini ortadan kaldırıyor. Yurt dışı sipariş ancak parça burada yoksa ve zaman varsa mantıklı.',
  },
  {
    kind: 'cards',
    names: ['Robot Wiring Guide', 'ESD Mitigation analizi', 'FTC Docs · Control System'],
    photo: { file: 'diagram.webp', alt: 'REV kontrol sistemi bağlantı şeması: batarya, şalter, Control Hub, motorlar, servo ve sensörler', fit: 'contain' },
    kicker: 'Mekanik — elektronik',
    title: 'Elektroniğin iki resmî dokümanı',
    lede: 'Sahada en çok zaman kaybettiren iki sorunun cevabı burada yazılı.',
    foot: 'Kuru kış aylarında saha kenarında kendiliğinden resetlenen robotların sebebi çoğu zaman ESD.',
    note: 'Elektronik ekibi bu iki dokümanı ilk hafta okusun.',
  },
  {
    kind: 'cards',
    names: ['Onshape', 'Autodesk Fusion · Inventor', 'SolidWorks', '2901 Purple Gears · Onshape kütüphanesi', '10650 Hazmat · GrabCAD arşivi', 'Blender4FTC · Fusion render rehberleri'],
    kicker: 'CAD',
    title: 'Profesyonel CAD, öğrenciye ücretsiz',
    lede: 'Çoğu öğrenci bu programlara bedava erişebileceğini bilmiyor.',
    foot: 'Asıl zamanı parça kütüphaneleri kazandırıyor: vidayı sıfırdan çizmek yerine hazır parçayı sürükleyip montaja geçiyorsunuz.',
    note: 'Render konusu CAD ile ödül tarafını birleştiren köprü.',
  },
  {
    kind: 'cards',
    names: ['ReCalc', 'How Gears Work', 'SDP-SI · KHK rehberleri', 'FRC Mechanism Encyclopedia'],
    art: 'gears',
    kicker: 'Mekanik',
    title: 'Tahmin etmeyi bırakıp hesaplamak',
    lede: 'Şasi hızı, motor seçimi, kaldırma yükü. Bunların hepsinin bir hesabı var.',
    foot: "Mekanik ekibin ilk refleksi 'deneyip görelim' değil, 'önce hesaplayalım' olmalı.",
    note: "How Gears Work'ü canlı açıp göstermeye değer.",
  },
  {
    kind: 'changes',
    items: ['interview', 'portfolio', 'awards'],
    photo: { file: 'juri', alt: 'Jüri, takımın robotunu masada incelerken not alıyor', pos: 'center 62%', short: true },
    kicker: 'Bu sezon ne değişti · 2',
    title: 'Jüri odası da değişti',
    lede: 'Görüşmenin adı, portfolyonun yeri ve ödül tablosu. Ödül ekibini en çok ilgilendiren üç kart.',
    foot: 'Initial Interview\'a katılmayan takım jüri ödüllerine aday olamıyor. Tarih çakışmasına dikkat.',
    note: 'Satıra tıklayınca büyür, tekrar tıklayınca kapanır. Motivate\'in bölünmesi DECODE\'dan; sunumda hâlâ eski adıyla anılıyorsa düzeltin. Hangi ödüllerin portfolyo istediğini ödül tablosundan okuyup portfolyo ekibine verin.',
  },
  {
    kind: 'awards',
    kicker: 'Ödüller ve jüri',
    title: 'Sahada üç kişi, jüride bütün takım',
    lede: "FTC'de bir üst seviyeye ilerlemenin ana yolu Inspire Award. Ve her ödül bir role denk geliyor.",
    foot: "Reach ve Sustain eski Motivate'in ikiye bölünmüş hâli. Promote ve Compass'ın bu sezonki durumu için tam manual'a bakın; müsabakadan Winning ve Finalist Alliance.",
    note: 'Yeni öğrencilerin en çok şaşırdığı bilgi. Erken ve net söylenmeli. Bu slayt robot dışı rolleri meşrulaştırıyor.',
  },
  {
    kind: 'cards',
    names: ['FTC Discord', 'Chief Delphi', 'Hivemind portfolyo arşivi', 'FTC Scout'],
    photo: { file: 'atolye', alt: 'Atölyede çalışan takım' },
    kicker: 'Katman 3 — canlı topluluk',
    title: 'Cevabı yazılmamış sorular',
    lede: 'Takıldığınızda tek başınıza değilsiniz. Soru sormak zayıflık değil, yöntem.',
    note: "Discord'a katılmak ilk hafta ödevlerinden biri.",
  },
  {
    kind: 'cards',
    names: ['FIRST Tech Challenge · YouTube', 'REV Robotics · YouTube', 'goBILDA · YouTube', '8644 Brainstormers · Tips & Tricks', '9794 Wizards.exe', 'Robot reveal videoları'],
    kicker: 'Katman 3 — video',
    title: 'İzleyerek öğrenilen kısım',
    lede: 'Bir mekanizmayı anlatan üç paragraf yerine, çalışırken gösteren otuz saniye.',
    foot: 'Bulduğunuz iyi videoyu takım Discord kanalına düşün. Üç ay sonra kimse "şu videoyu bir yerde görmüştüm" demek zorunda kalmasın.',
    note: 'Video kaynakları yeni öğrencinin en hızlı öğrendiği format.',
  },
  {
    kind: 'adopt',
    target: '#atlas-host',
    kicker: 'Atlas',
    title: 'Hepsi burada, sezon boyunca açık',
    note: 'Canlı gösterin: arama kutusuna bir şey yazın, katman çipine basın. Slayttaki link tıklanmaz, buradaki tıklanır.',
    wide: true,
  },
  {
    kind: 'adopt',
    target: '#tasks-host',
    kicker: 'Bu hafta',
    title: 'Görevle çıkın, listeyle değil',
    lede: 'Beşi de bu hafta bitecek. Toplamı bir akşam sürüyor.',
    note: 'Sunumun en önemli slaydı. Herkes buradan somut bir görevle çıkmalı.',
  },
  {
    kind: 'closing',
    photo: { file: 'takim', alt: 'Takım fotoğrafı', bg: true },
    title: ['Robot sezonluk,', 'öğrendikleriniz', 'kalıcı.'],
    lede: 'Aralıkta bu robot rafa kalkacak; nerede ne öğreneceğinizi bilmek mezun olana kadar sizinle. Bildiğinizi paylaşın, bilmediğinizi sorun.',
    foot: 'More than robots · AG Robotik · ALKEV Okulları · BIOBUZZ 2026–2027',
    note: 'Kapanış. Duvardaki yazı FIRST\'ın kendi sözü: More than robots. Son cümle Gracious Professionalism\'in kısa hâli. Sorulara geçin.',
  },
];
