/**
 * Sunum modunun slayt listesi.
 *
 * İçerik data.js'ten gelir; burada yalnızca hangi slaytta ne gösterileceği
 * ve konuşmacı notu durur. Notlar sunumun kendi konuşmacı notlarından.
 */

export const SLIDES = [
  {
    kind: 'cover',
    eyebrow: 'AG Robotik · Sezon açılışı · 12 Eylül 2026',
    title: ['FTC Kaynakları ve', 'Eğitim Materyalleri'],
    lede: 'Yeni sezona başlarken neyi, nereden öğreneceğiz?',
    foot: 'BIOBUZZ · 2026–2027 FIRST® CANOPY sezonu · Hakan Ataş · ALKEV Okulları',
    note: 'Açılış. Bugün sezonun açıldığı gün. Sunumun amacı oyunu anlatmak değil, bu sezon boyunca hangi kaynaklara nasıl ulaşacağımızı öğretmek.',
  },
  {
    kind: 'facts',
    kicker: 'Bugün neredeyiz',
    title: 'Sezon bugün açıldı',
    lede: 'Yani bu sunum bir kütüphane turu değil, bu haftanın yol haritası.',
    callout: "Oyun her yıl değişir, kaynaklar değişmez. BIOBUZZ'ın kuralları bu sezona özel; bugün öğreneceğiniz kaynak haritası mezun olana kadar aynı kalacak.",
    note: 'Öğrencilerin ilk hafta hatası: oyunu ezberlemeye çalışmak. Asıl kazanç kaynak refleksini kurmak.',
  },
  {
    kind: 'two',
    kicker: 'Zihin haritası',
    title: 'İki tür kaynak vardır',
    lede: 'Hangisine ne kadar zaman ayıracağınızı bu ayrım belirler.',
    note: 'Sağ sütun bu sunumun asıl konusu. Sol sütun zaten mecburen okunacak.',
  },
  {
    kind: 'layers',
    kicker: 'Kaynak ekosistemi',
    title: 'Her kaynağın bir sahibi var',
    lede: '60 link ezberlemeyin, üç katmanı öğrenin.',
    note: 'Bu slayt sunumun omurgası. Sonraki her slaydı bir katmana yerleştireceğiz.',
  },
  {
    kind: 'adopt',
    target: '.quiz',
    kicker: 'Kural gücü',
    title: 'Tartışmayı hangisi bitirir?',
    note: 'Salona sorun, cevabı aldıktan sonra tıklayın. “gm0’da böyle yazıyor” geçerli bir argüman değildir; “Manual’ın şu maddesi” geçerlidir.',
  },
  {
    kind: 'cards',
    names: ['Competition Manual', 'FTC Q&A', 'FTC Events'],
    kicker: 'Katman 1 — resmî FIRST',
    title: 'Kuralın tek kaynağı',
    lede: 'Buradan gelen bilgi bağlayıcıdır; gerisi yorumdur.',
    foot: 'Bu üç adres sezon boyunca açık sekmede durmalı.',
    note: "Q&A vurgulanmalı: yeni takımların en çok kaçırdığı resmî kaynak. Cevapları Manual kadar bağlayıcı.",
  },
  {
    kind: 'cards',
    names: ['FTC Docs', 'FTC Docs · Control System', 'FTC Docs · SDK', 'FTC Docs · Vision', 'FTC Docs · CAD ve üretim', 'Robot Wiring Guide'],
    kicker: 'Katman 1 — resmî FIRST',
    title: 'FTC Docs: teknik tarafın resmî evi',
    lede: 'Çoğu yeni takımın hiç açmadan sezona girdiği kaynak.',
    foot: 'Vision bölümü ayrı bir parantez hak ediyor: AprilTag ve VisionPortal artık otonom performansının belirleyicisi.',
    note: 'Bu sayfa yazılım ekibinin ilk hafta okuma listesi.',
  },
  {
    kind: 'cards',
    names: ['FTC Türkiye'],
    kicker: 'Katman 1 — yerel',
    title: 'Türkçe giriş katmanı',
    lede: 'İngilizce kaynak yığınına dalmadan önce buradan başlamak işi kolaylaştırır.',
    bullets: [
      "FTC'ye İlk Adım — programa sıfırdan giriş",
      'Takım Kayıt Kılavuzu — kayıt sürecinin adımları',
      'BIOBUZZ Kickoff sayfası ve sezon kütüphanesi',
      'Türkçe ödül tanımları — jürinin neye baktığı',
      'Parça tedarikçileri listesi ve Off-Season rehberi',
    ],
    foot: "Yine de nihai kural kaynağı İngilizce Competition Manual'dır. Türkçe kaynaklar giriş kapısıdır, son söz değil.",
    note: 'Yeni öğrenci için psikolojik olarak önemli: her şey İngilizce değil. Ama son sözü Manual söyler.',
  },
  {
    kind: 'cards',
    names: ['Game Manual 0', 'gm0 · Getting Started in FTC', 'gm0 · Kit and Hardware Guide', 'gm0 · Mechanical Design', 'gm0 · Software Concepts', 'gm0 · Useful Resources'],
    kicker: 'Katman 2 — topluluk dokümanı',
    title: 'Tek bir link alacaksanız, bu olsun',
    lede: "Game Manual 0: açık kaynak, topluluk tarafından sürekli güncellenen, FTC'nin fiilî ders kitabı.",
    note: 'Bu slaytta gerçekten siteyi açıp Useful Resources sayfasını gösterin.',
  },
  {
    kind: 'paths',
    kicker: 'Yazılım',
    title: 'Üç programlama yolu, tek yolculuk',
    lede: 'Hepsi aynı robotu sürer. Fark, ne kadar kontrol istediğinizde.',
    foot: "Java'yı sıfırdan öğrenmek için: Learn Java for FTC · REV Introduction to Programming · FtcRobotController deposu.",
    note: "Kimse Android Studio'dan başlamak zorunda değil, ama sezon ortasında oraya geçeceğiz.",
  },
  {
    kind: 'cards',
    names: ['FTCLib / SolversLib', 'Road Runner', 'Pedro Pathing', 'NextFTC', 'VisionPortal · EasyOpenCV', 'FTC Dashboard · Panels'],
    kicker: 'Yazılım',
    title: 'Kütüphane haritası',
    lede: 'Bugün kullanmayacaksınız. Ama adını duyduğunuzda ne olduğunu bilin.',
    foot: "Ders: FTCLib'den SolversLib'e geçiş gösteriyor ki kütüphaneler yaşar ve ölür. Seçmeden önce bakımının sürdüğünü kontrol edin.",
    note: "Yeni öğrenciye kaygı vermeden 'var olduğunu bilin' tonuyla geçin.",
  },
  {
    kind: 'cards',
    names: ['goBILDA', 'REV Robotics', 'TETRIX (Pitsco)', 'AndyMark', 'Studica'],
    kicker: 'Mekanik — tedarik',
    title: 'Beş yapı sistemi, tek saha',
    lede: 'Starter kit sadece giriş kapısı. Beşi de legal ve sahada yan yana yarışıyor.',
    foot: "Sistemler karışabilir. Seçimi marka sadakati değil; elinizdeki parça, bütçe ve teslim süresi belirler. gm0'ın Kit and Hardware Guide bölümü karşılaştırmayı tarafsız yapıyor.",
    note: 'Önemli düzeltme: FTC iki markadan ibaret değil. Takımımızın elindeki mevcut parçalar seçimi büyük ölçüde belirliyor.',
  },
  {
    kind: 'supply',
    kicker: 'Mekanik — tedarik',
    title: 'Önce Türkiye, sonra yurt dışı',
    lede: "FTC Türkiye'nin kendi tedarikçi listesi var: NFR Products, Robopiece, Wattos Otomasyon. Sipariş yolculuğu oradan başlar.",
    foot: 'Yurt dışı: yapı sistemi için goBILDA, REV, Pitsco, AndyMark, Studica · servo ve hareket için ServoCity, Actuonix, Axon · ham malzeme için McMaster-Carr, OnlineMetals, MiSUMi, Fastenal.',
    note: 'Türkiye tedarikçileri kargo ve gümrük derdini ortadan kaldırıyor. Yurt dışı sipariş ancak parça burada yoksa ve zaman varsa mantıklı.',
  },
  {
    kind: 'cards',
    names: ['Robot Wiring Guide', 'ESD Mitigation analizi', 'FTC Docs · Control System'],
    kicker: 'Mekanik — elektronik',
    title: 'Elektroniğin iki resmî dokümanı',
    lede: 'Sahada en çok zaman kaybettiren iki sorunun cevabı burada yazılı.',
    foot: 'Kuru kış aylarında saha kenarında kendiliğinden resetlenen robotların sebebi çoğu zaman ESD.',
    note: 'Elektronik ekibi bu iki dokümanı ilk hafta okusun.',
  },
  {
    kind: 'cards',
    names: ['Onshape', 'Autodesk Fusion · Inventor', 'PTC Creo', 'SolidWorks', '2901 Purple Gears · Onshape kütüphanesi', '10650 Hazmat · GrabCAD arşivi', 'ServoCity CAD dosyaları', 'Blender4FTC · Fusion render rehberleri'],
    kicker: 'CAD',
    title: 'Profesyonel CAD, öğrenciye ücretsiz',
    lede: 'Çoğu öğrenci bu programlara bedava erişebileceğini bilmiyor.',
    foot: 'Asıl zamanı parça kütüphaneleri kazandırıyor: vidayı sıfırdan çizmek yerine hazır parçayı sürükleyip montaja geçiyorsunuz.',
    note: 'Render konusu CAD ile ödül tarafını birleştiren köprü.',
  },
  {
    kind: 'cards',
    names: ['ReCalc · EveryCalc', 'How Gears Work', 'SDP-SI · KHK rehberleri', 'FRC Mechanism Encyclopedia'],
    kicker: 'Mekanik',
    title: 'Tahmin etmeyi bırakıp hesaplamak',
    lede: 'Şasi hızı, motor seçimi, kaldırma yükü. Bunların hepsinin bir hesabı var.',
    foot: "Mekanik ekibin ilk refleksi 'deneyip görelim' değil, 'önce hesaplayalım' olmalı.",
    note: "How Gears Work'ü canlı açıp göstermeye değer.",
  },
  {
    kind: 'awards',
    kicker: 'Ödüller ve jüri',
    title: 'Şampiyonluk maçtan geçmiyor',
    lede: "FTC'de bir üst seviyeye ilerlemenin ana yolu Inspire Award. Ve her ödül bir role denk geliyor.",
    foot: "Ayrıca Promote, Compass ve Judges' Choice · müsabakadan Winning ve Finalist Alliance.",
    note: 'Yeni öğrencilerin en çok şaşırdığı bilgi. Erken ve net söylenmeli. Bu slayt robot dışı rolleri meşrulaştırıyor.',
  },
  {
    kind: 'cards',
    names: ['FTC Discord', 'Chief Delphi', 'Hivemind portfolyo arşivi', 'FTC Scout'],
    kicker: 'Katman 3 — canlı topluluk',
    title: 'Cevabı yazılmamış sorular',
    lede: 'Takıldığınızda tek başınıza değilsiniz. Soru sormak zayıflık değil, yöntem.',
    note: "Discord'a katılmak ilk hafta ödevlerinden biri.",
  },
  {
    kind: 'cards',
    names: ['FIRST Tech Challenge · YouTube', 'REV Robotics · YouTube', 'goBILDA · YouTube', '8644 Brainstormers · Tips & Tricks', '9794 Wizards.exe', 'Robot reveal videoları'],
    kicker: 'Katman 3 — video',
    title: 'İzleyerek öğrenilen kısım',
    lede: 'Bir mekanizmayı anlatan üç paragraf yerine, çalışırken gösteren otuz saniye.',
    foot: 'Bulduğunuz iyi videoyu takım Discord kanalına düşün. Altı ay sonra kimse "şu videoyu bir yerde görmüştüm" demek zorunda kalmasın.',
    note: 'Video kaynakları yeni öğrencinin en hızlı öğrendiği format.',
  },
  {
    kind: 'adopt',
    target: '#atlas-host',
    kicker: 'Atlas',
    title: 'Hepsi burada, sezon boyunca açık',
    note: 'Canlı gösterin: arama kutusuna bir şey yazın, katman çipine basın. Slayttaki link tıklanmaz, buradaki tıklanır.',
    wide: true,
  },
  {
    kind: 'adopt',
    target: '#tasks-host',
    kicker: 'Bu hafta',
    title: 'Görevle çıkın, listeyle değil',
    lede: 'Beşi de bu hafta bitecek. Toplamı bir akşam sürüyor.',
    note: 'Sunumun en önemli slaydı. Herkes buradan somut bir görevle çıkmalı.',
  },
  {
    kind: 'closing',
    title: ['İyi takımlar iyi', 'robot yapmaz —', 'iyi öğrenir.'],
    lede: 'Bu sezon elimizdeki en büyük avantaj, sorunun cevabının nerede olduğunu bilmek. Gerisi çalışmak.',
    foot: 'AG Robotik · ALKEV Okulları · BIOBUZZ 2026–2027',
    note: 'Kapanış. Sorulara geçin.',
  },
];
